apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventportal-db
  labels:
    app: eventportal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventportal-db
  template:
    metadata:
      labels:
        app: eventportal-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres_password
            - name: POSTGRES_DB
              value: "smarteventportal"
