apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  # This matches the POSTGRES_PASSWORD in your docker-compose.yml
  database_url: "postgresql://postgres:password@eventportal-db:5432/smarteventportal?schema=public"
  postgres_password: "password"
